sudo: false

language: rust
rust: nightly

addons:
  apt:
    packages:
      - libpam0g-dev
  
git:
  depth: 1

script:
- cargo build --verbose
- rustfmt --write-mode checkstyle src/pam_setquota.rs > /dev/null
